# name: deploy

# on:
#   push:
#     branches: [ master ]

#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: api-gateway
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}
#           port: 22
#           script: |
#             cd /home/cowik/prod/microservice-project/api-gateway
#             git pull origin master
#             npm install
#             npm run start:production